[book]
title = "RuchyRuchy Bootstrap Compiler: A TDD Journey"
authors = ["Noah Gift", "Claude Code"]
description = "Building a bootstrap compiler for Ruchy using Test-Driven Development and pure Ruchy dogfooding"
language = "en"
multilingual = false
src = "book/src"

[build]
build-dir = "book/book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/paiml/ruchyruchy"
edit-url-template = "https://github.com/paiml/ruchyruchy/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
