# PMAT TDG Enforcement Configuration for RuchyRuchy
# Generated: 2025-10-29
# PMAT Version: v2.180.1
# Project: ruchyruchy (Educational bootstrap compiler + QUALITY tools)

[quality_gates]
# Minimum grade for Rust code (A, B+, B, etc.)
rust_min_grade = "B+"

# Maximum score drop allowed (prevents regressions)
max_score_drop = 5.0

# Enforcement mode: "strict" (fail on violation), "warning" (report only)
# Start with "warning" for 2-3 weeks, then switch to "strict"
mode = "warning"

# Fail build if new files don't meet minimum grade
fail_on_new_files_below_min = true

[baseline]
# Path to baseline file (created by: pmat tdg baseline create)
baseline_path = ".pmat/tdg-baseline.json"

# Auto-update baseline when merging to main branch
auto_update_on_main = true

# Git branch considered "main" for auto-updates
main_branch = "main"

[analysis]
# Paths to analyze (relative to repository root)
paths = ["src/"]

# Paths to exclude from analysis
exclude_paths = [
    "target/",
    "build/",
    ".git/",
    "validation/",  # Pure Ruchy test files (not Rust)
]

# File patterns to exclude
exclude_patterns = [
    "**/tests.rs",  # Test files can be more lenient
    "**/*_test.rs",
]

[reporting]
# Show detailed breakdown in reports
show_details = true

# Include file-by-file scores in reports
show_file_scores = true

# Report format: "text", "json", "markdown"
report_format = "text"

[ci_cd]
# Post PR comments with quality reports
post_pr_comments = true

# Fail CI/CD pipeline on regressions
fail_on_regression = true

# Fail CI/CD pipeline if below minimum grade
fail_on_below_min = true

[metrics]
# Track quality score trends over time
enable_trend_tracking = true

# Store historical scores
history_path = ".pmat/tdg-history.json"

# Maximum history entries to keep (0 = unlimited)
max_history_entries = 100

[notifications]
# Notify on significant quality improvements (optional)
notify_on_improvement = false

# Notify on quality regressions (optional)
notify_on_regression = false

# --- RuchyRuchy-Specific Notes ---
#
# Current Baseline: 95.2 average score (A+ grade)
# Files analyzed: 14 Rust files in src/
# Files skipped: 1 (src/complete_bootstrap_demo.rs - parse error)
#
# Quality Profile:
# - High-quality codebase (EXTREME TDD methodology)
# - 470 comprehensive validations (QUALITY tools)
# - Zero technical debt (SATD=0)
# - A+ lint grade
#
# Recommended Workflow:
# 1. Week 1-3: Keep mode = "warning" (team adjustment)
# 2. Week 4: Switch to mode = "strict" (enforcement active)
# 3. Monitor: Review .pmat/tdg-history.json for trends
#
# Integration with QUALITY Tools:
# - PMAT TDG: Rust code quality (this config)
# - QUALITY-001: Ruchy code TDG (our tool)
# - Combined: Full-stack quality for Rust + Ruchy
