[book]
title = "RuchyRuchy: Educational Bootstrap Compiler"
authors = ["RuchyRuchy Development Team"]
language = "en"
multilingual = false
src = "src"
description = "Complete documentation of the RuchyRuchy bootstrap compiler built with EXTREME TDD methodology"

[build]
build-dir = "book"
create-missing = true

[preprocessor.index]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/paiml/ruchyruchy"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/paiml/ruchyruchy/edit/main/book/{path}"
site-url = "/ruchyruchy/"
cname = "ruchyruchy.paiml.com"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
